export const techs = {
  cva: {
    id: 'cva',
    name: 'Class Variance Authority',
    src: 'tech/cva.svg',
    size: 'sm',
    techColor: 'next',
    bgColor: 'whiteLogo',
    mt: 'auto',
  },
  styledComponents: {
    id: 'styledComponents',
    name: 'Styled Components',
    src: 'tech/styledcomponents.svg',
    size: 'sm',
    techColor: 'styledComponents',
    bgColor: 'pinkLogo',
  },
  framerMotion: {
    id: 'framerMotion',
    name: 'Framer Motion',
    src: 'tech/framer-motion.svg',
    size: 'sm',
    techColor: 'motion',
    bgColor: 'pinkLogo',
  },
  reactHookForm: {
    id: 'reactHookForm',
    name: 'React Hook Form',
    src: 'tech/reacthookform.svg',
    size: 'sm',
    techColor: 'graphql',
    bgColor: 'pinkLogo',
    marginLeft: 'auto',
  },
  storybook: {
    id: 'storybook',
    name: 'Storybook',
    src: 'tech/storybook.svg',
    size: 'md',
    techColor: 'storybook',
    bgColor: 'pinkLogo',
  },
  cypress: {
    id: 'cypress',
    name: 'Cypress',
    src: 'tech/cypress.svg',
    size: 'sm',
    techColor: 'cypress',
    bgColor: 'greenLogo',
  },
  reactTestingLibrary: {
    id: 'reactTestingLibrary',
    name: 'React Testing Library',
    src: 'tech/testinglibrary.svg',
    size: 'sm',
    techColor: 'testingLibrary',
    bgColor: 'redLogo',
  },
  git: {
    id: 'git',
    name: 'Git',
    src: 'tech/git.svg',
    size: 'md',
    techColor: 'git',
    bgColor: 'orangeLogo',
  },
  nest: {
    id: 'nest',
    name: 'Nest',
    src: 'tech/nestjs.svg',
    size: 'md',
    techColor: 'nest',
    bgColor: 'redLogo',
    mt: 'auto',
  },
  fastify: {
    id: 'fastify',
    name: 'Fastify',
    src: 'tech/fastify.svg',
    size: 'sm',
    techColor: 'next',
    bgColor: 'whiteLogo',
    mt: 'auto',
  },

  unocss: {
    id: 'unocss',
    name: 'Uno CSS',
    src: 'tech/unocss.svg',
    size: 'sm',
    techColor: 'unocss',
    bgColor: 'whiteLogo',
  },
  pandacss: {
    id: 'pandacss',
    name: 'Panda CSS',
    src: 'tech/pandacss.svg',
    size: 'sm',
    techColor: 'panda',
    bgColor: 'yellowLogo',
  },
  tailwindcss: {
    id: 'tailwindcss',
    name: 'Tailwind CSS',
    src: 'tech/tailwind-css.svg',
    size: 'md',
    techColor: 'tailwind',
    bgColor: 'blueLogo',
  },
  expo: {
    id: 'expo',
    name: 'Expo',
    src: 'tech/expo.svg',
    size: 'sm',
    techColor: 'next',
    bgColor: 'whiteLogo',
  },
  qwik: {
    id: 'qwik',
    name: 'Qwik',
    src: 'tech/qwik.svg',
    size: 'sm',
    techColor: 'qwik',
    bgColor: 'purpleLogo',
  },
  react: {
    id: 'react',
    name: 'React',
    src: 'tech/react.svg',
    size: 'lg',
    techColor: 'react',
    bgColor: 'blueLogo',
  },
  jest: {
    id: 'jest',
    name: 'Jest',
    src: 'tech/jest.svg',
    size: 'sm',
    techColor: 'jest',
    bgColor: 'pinkLogo',
  },
  vitest: {
    id: 'vitest',
    name: 'Vitest',
    src: 'tech/vitest.svg',
    size: 'sm',
    techColor: 'vitest',
    bgColor: 'greenLogo',
  },
  typescript: {
    id: 'typescript',
    name: 'Typescript',
    src: 'tech/typescript.svg',
    size: 'md',
    techColor: 'typescript',
    bgColor: 'blueLogo',
  },
  nodejs: {
    id: 'nodejs',
    name: 'NodeJS',
    src: 'tech/nodejs-icon.svg',
    size: 'md',
    techColor: 'node',
    bgColor: 'greenLogo',
  },
  redis: {
    id: 'redis',
    name: 'Redis',
    src: 'tech/redis.svg',
    size: 'sm',
    techColor: 'redis',
    bgColor: 'redLogo',
  },
  sequelize: {
    id: 'sequelize',
    name: 'Sequelize',
    src: 'tech/sequelize.svg',
    size: 'sm',
    techColor: 'sequelize',
    bgColor: 'blueLogo',
  },
  socketio: {
    id: 'socketio',
    name: 'Socket.io',
    src: 'tech/socketdotio.svg',
    size: 'sm',
    techColor: 'next',
    bgColor: 'whiteLogo',
  },
  prisma: {
    id: 'prisma',
    name: 'Prisma',
    src: 'tech/prisma.svg',
    size: 'md',
    techColor: 'prisma',
    bgColor: 'blueLogo',
  },
  reactNative: {
    id: 'reactNative',
    name: 'React Native',
    src: 'tech/react-native.svg',
    size: 'md',
    techColor: 'react',
    bgColor: 'blueLogo',
  },
  nextJs: {
    id: 'nextJs',
    name: 'Next.js',
    src: 'tech/next-js.svg',
    size: 'lg',
    techColor: 'next',
    bgColor: 'whiteLogo',
  },
  radixui: {
    id: 'radixui',
    name: 'Radix UI',
    src: 'tech/radix-ui.svg',
    size: 'md',
    techColor: 'radix',
    bgColor: 'whiteLogo',
  },
  stitches: {
    id: 'stitches',
    name: 'Stitches',
    src: 'tech/stitches.svg',
    size: 'sm',
    techColor: 'radix',
    bgColor: 'whiteLogo',
  },
  figma: {
    id: 'figma',
    name: 'Figma',
    src: 'tech/figma.svg',
    size: 'sm',
    techColor: 'figma',
    bgColor: 'redLogo',
  },
  reactQuery: {
    id: 'reactQuery',
    name: 'React Query',
    src: 'tech/reactquery.svg',
    size: 'sm',
    techColor: 'reactQuery',
    bgColor: 'redLogo',
  },
  graphql: {
    id: 'graphql',
    name: 'Graphql',
    src: 'tech/graphql.svg',
    size: 'sm',
    techColor: 'graphql',
    bgColor: 'pinkLogo',
  },
  novu: {
    id: 'novu',
    name: 'Novu',
    src: 'tech/novu.svg',
    size: 'sm',
    techColor: 'novu',
    bgColor: 'redLogo',
  },
  postgresql: {
    id: 'postgresql',
    name: 'Postgres',
    src: 'tech/postgresql.svg',
    size: 'md',
    techColor: 'postgres',
    bgColor: 'blueLogo',
  },
  firebase: {
    id: 'firebase',
    name: 'Firebase',
    src: 'tech/firebase.svg',
    size: 'sm',
    techColor: 'firebase',
    bgColor: 'yellowLogo',
  },
  docker: {
    id: 'docker',
    name: 'Docker',
    src: 'tech/docker.svg',
    size: 'sm',
    techColor: 'docker',
    bgColor: 'blueLogo',
  },
  kafka: {
    id: 'kafka',
    name: 'Apache Kafka',
    src: 'tech/apachekafka.svg',
    size: 'sm',
    techColor: 'next',
    bgColor: 'whiteLogo',
  },
} as const
