export const techs = [
  { name: 'React', size: 'lg' },
  { name: 'Next', size: 'lg' },

  { name: 'React Native', size: 'md' },

  { name: 'Typescript', size: 'md' },
  { name: 'Node', size: 'md' },
  { name: 'Prisma', size: 'md' },
  { name: 'PostgreSQL', size: 'md' },
  { name: 'Express', size: 'md' },

  { name: 'Tailwind', size: 'md' },
  { name: 'Storybook', size: 'md' },
  { name: 'Radix UI', size: 'md' },
  { name: 'Framer Motion', size: 'md' },

  { name: 'Pandacss', size: 'sm' },
  { name: 'React Query', size: 'sm' },
  { name: 'Axios', size: 'sm' },
  { name: 'React Hook Form', size: 'sm' },
  { name: 'React Testing Library', size: 'sm' },
  { name: 'Jest', size: 'sm' },
  { name: 'Zod', size: 'sm' },
  { name: 'Expo', size: 'sm' },
  { name: 'Styled Components', size: 'sm' },
  { name: 'Vitest', size: 'sm' },
  { name: 'Cypress', size: 'sm' },
  { name: 'CVA', size: 'sm' },
  { name: 'Uno CSS', size: 'sm' },
  { name: 'Chakra UI', size: 'sm' },
  { name: 'Qwik', size: 'sm' },
  { name: 'NestJS', size: 'sm' },
  { name: 'Fastify', size: 'sm' },
  { name: 'Sequelize', size: 'sm' },
  { name: 'Typeorm', size: 'sm' },
  { name: 'Kafka', size: 'sm' },
  { name: 'GraphQL', size: 'sm' },
]
